import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { ThemeScript } from "./theme-script"
import { ThemeToggle } from "@/components/theme-toggle"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en" suppressHydrationWarning>
    <head>
      <ThemeScript />
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <header className="flex items-center justify-end p-4 border-b">
          <ThemeToggle />
        </header>
      <main>{children}</main>  
      </body>
    </html>;
}